### ISSUE TITLE
[Bug]: Unknown Error: 'tracker'

### ISSUE THREAD

**Issue by alex036** [StuffAnThings/qbit_manage#171]
### Describe the Bug

When running any sort of command, I get:
```
| Unknown Error: 'tracker'                                                                           |
| Traceback (most recent call last):                                                                 |
|   File "/root/qbit_manage/modules/qbittorrent.py", line 571, in rem_unregistered                   |
|     tracker = self.config.get_tags([x.url])                                                        |
|   File "/root/qbit_manage/modules/config.py", line 342, in get_tags                                |
|     tracker['tag'] = self.util.check_for_attribute(self.data, "tag", parent="tracker", subparent=default_tag, default=default_tag, var_type="list") |
|   File "/root/qbit_manage/modules/util.py", line 66, in check_for_attribute                        |
|     if subparent not in yaml.data[parent] or not yaml.data[parent][subparent]:                     |
|   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/comments.py", line 927, in __getitem__  |
|     return ordereddict.__getitem__(self, key)                                                      |
| KeyError: 'tracker'
```

### Logs

https://gist.github.com/alex036/d4a405681951ccb49e64b395a462ba59

### Installation

Local

### Version Number

3.3.0

### What branch are you on?

master

**Comment by bakerboy448** [comment]
Why are you using the ancient version of Qbit 4.2.5?

**Comment by alex036** [comment]
> Why are you using the ancient version of Qbit 4.2.5?

Is there a minimum version I should be using for this script? There was no docs I could find that mentioned a minimum.

**Comment by bakerboy448** [comment]
4.3 made various breaking changes from 4.2.5, so certain assumptions about values etc may not be broken.

**Comment by bakerboy448** [comment]
@bobokun  can you add a version check and require Qbit 4.30+

just require webapi 2.6.1 as min.

x-ref sonarr fix and api version for 4.3
https://github.com/Sonarr/Sonarr/pull/3346/files

x-ref previous user on 4.2.5
https://github.com/StuffAnThings/qbit_manage/issues/159

**Comment by alex036** [comment]
Still getting an error:

```
                   |_|        |______|                          |___/                          |
|     Version: 3.3.0                                                                                 |
|====================================================================================================|
|     --run (QBT_RUN): True                                                                          |
|     --schedule (QBT_SCHEDULE): 1440                                                                |
|     --startup-delay (QBT_STARTUP_DELAY): 0                                                         |
|     --config-file (QBT_CONFIG): ['config.yml']                                                     |
|     --log-file (QBT_LOGFILE): qbit_manage.log                                                      |
|     --cross-seed (QBT_CROSS_SEED): False                                                           |
|     --recheck (QBT_RECHECK): False                                                                 |
|     --cat-update (QBT_CAT_UPDATE): False                                                           |
|     --tag-update (QBT_TAG_UPDATE): False                                                           |
|     --rem-unregistered (QBT_REM_UNREGISTERED): True                                                |
|     --tag-tracker-error (QBT_TAG_TRACKER_ERROR): False                                             |
|     --rem-orphaned (QBT_REM_ORPHANED): False                                                       |
|     --tag-nohardlinks (QBT_TAG_NOHARDLINKS): False                                                 |
|     --skip-cleanup (QBT_SKIP_CLEANUP): False                                                       |
|     --dry-run (QBT_DRY_RUN): True                                                                  |
|     --log-level (QBT_LOG_LEVEL): DEBUG                                                             |
|     --divider (QBT_DIVIDER): =                                                                     |
|     --width (QBT_WIDTH): 100                                                                       |
|     --debug (QBT_DEBUG): False                                                                     |
|     --trace (QBT_TRACE): False                                                                     |
|                                                                                                    |
|     Run Mode: Script will exit after completion.                                                   |
|====================================================================================================|
|                                            Starting Run                                            |
|====================================================================================================|
| Locating config...                                                                                 |
| Using /root/qbit_manage/config/config.yml as config                                                |
| Connecting to Qbittorrent...                                                                       |
| Host: localhost:10xxx, Username: (redacted), Password: (redacted)                                  |
| qBittorrent: v4.4.5                                                                                |
| qBittorrent Web API: 2.8.5                                                                         |
| qbit_manage support version: v4.4.5                                                                |
| Qbt Connection Successful                                                                          |
|======================================= Getting Torrent List =================
```

```
Unknown Error: 'tracker'                                                                           |
| Traceback (most recent call last):                                                                 |
|   File "/root/qbit_manage/modules/qbittorrent.py", line 571, in rem_unregistered                   |
|     tracker = self.config.get_tags([x.url])                                                        |
|   File "/root/qbit_manage/modules/config.py", line 342, in get_tags                                |
|     tracker['tag'] = self.util.check_for_attribute(self.data, "tag", parent="tracker", subparent=default_tag, default=default_tag, var_type="list") |
|   File "/root/qbit_manage/modules/util.py", line 66, in check_for_attribute                        |
|     if subparent not in yaml.data[parent] or not yaml.data[parent][subparent]:                     |
|   File "/usr/local/lib/python3.8/dist-packages/ruamel/yaml/comments.py", line 927, in __getitem__  |
|     return ordereddict.__getitem__(self, key)                                                      |
| KeyError: 'tracker'                                                                                |
|                                                                                                    |
| Unknown Error: 'tracker'                                                                           |
| No unregistered torrents found.
```

My config:
```
#commands:
  # The commands defined below will IGNORE any commands used in command line and docker env variables.
  #dry_run: false
  #rem_unregistered: true
qbt:
  # qBittorrent parameters
  host: localhost:10xxx
  user: xxx
  pass: xxx


directory:
  # Do not remove these
  # Cross-seed var: </your/path/here/>  # Output directory of cross-seed
  # root_dir var: </your/path/here/>  # Root downloads directory used to check for orphaned files, noHL, and RecycleBin.
  # <OPTIONAL> remote_dir var: </your/path/here/>  # Path of docker host mapping of root_dir.
  # Must be set if you're running qbit_manage locally and qBittorrent/cross_seed is in a docker
  # <OPTIONAL> recycle_bin var: </your/path/here/>   # Path of the RecycleBin folder. Default location is set to remote_dir/.RecycleBin
  # <OPTIONAL> torrents_dir var: </your/path/here/>  # Path of the your qbittorrent torrents directory. Required for `save_torrents` attribute in recyclebin

  cross_seed: /home/xxx/torrents/qbittorrent/
  root_dir: /home/xxx/torrents/qbittorrent/
  #remote_dir: "/mnt/user/data/torrents/"
  #recycle_bin: "/mnt/user/data/torrents/.RecycleBin"
  #torrents_dir: "/qbittorrent/data/BT_backup"
  #orphaned_dir: "/data/torrents/orphaned_data"


  remote_dir: /home/xxx/torrents/qbittorrent/
  recycle_bin: /home/xxx/torrents/qbittorrent/.RecycleBin
  torrents_dir:
settings:
  force_auto_tmm: false
  tracker_error_tag: issue
  ignoreTags_OnUpdate:
  - noHL
  - issue
  - cross-seed
webhooks:
  error:
  run_start:
  run_end:
  function:
    cross_seed:
    recheck:
    cat_update:
    tag_update:
    rem_unregistered:
    tag_tracker_error:
    rem_orphaned:
    tag_nohardlinks:
    cleanup_dirs:
recyclebin:
  enabled: true
  empty_after_x_days:
  save_torrents: false
  split_by_category: false
orphaned:
  empty_after_x_days:
  exclude_patterns:
```

**Comment by bobokun** [comment]
Your config is missing `tracker`
https://github.com/StuffAnThings/qbit_manage/blob/04c1dfb79a9824637357a8d1d16faa92a42079df/config/config.yml.sample#L64-L128

**Comment by alex036** [comment]
Thanks, fixed now.
