### ISSUE TITLE
[Bug]: Windows - tags

### ISSUE THREAD

**Issue by pax0707** [StuffAnThings/qbit_manage#186]
### Describe the Bug

Dealing with tags is broken under windows.

```
 Uncaught Exception                                                                                 |
Traceback (most recent call last):
  File "qbit_manage.py", line 539, in <module>
    start_loop()
  File "qbit_manage.py", line 306, in start_loop
    start()
  File "qbit_manage.py", line 390, in start
    num_added, num_tagged = cfg.qbt.cross_seed()
  File "D:\Software\qbit_manage\modules\qbittorrent.py", line 848, in cross_seed
    tracker = self.config.get_tags([x.url for x in torrent.trackers if x.url.startswith("http")])
  File "D:\Software\qbit_manage\modules\config.py", line 544, in get_tags
    default_tag = tracker["url"].split(os.sep)[2].split(":")[0]
IndexError: list index out of range
```

### Logs

+

### Installation

Local

### Version Number

3.3.1

### What branch are you on?

master

**Comment by bobokun** [comment]
please share full logs and your config

**Comment by pax0707** [comment]
Didn't clean up from the config sample.

Error still stands.

**Comment by bobokun** [comment]
Like @bakerboy448 mentioned, it's difficult to identify the issue with the censored logs. Can you share what the torrent url looks like?

**Comment by bakerboy448** [comment]
--trace then hopefully

Also please answer the other questions from the other comment

**Comment by bobokun** [comment]
also I just noticed in your cat section you should remove the two keys `movies` and `tv`. You should also remove the `cat_change:` if you aren't using it.

**Comment by bobokun** [comment]
uh...and also in your command section...
`tag_update: trues` should be `tag_update: true`

**Comment by pax0707** [comment]
Trace shows it.
It looks like I have a few public torrents which I didn't have tags defined for.
When it hits one of those it errors.

**Comment by bobokun** [comment]
It should be default tag as other if it's not defined.

**Comment by pax0707** [comment]
Example: arenabg is something public I don't have defined.

```
                                                                                                    |
| JSON: {'function': 'tag_update', 'title': 'Updating Tags', 'body': '   Torrent Name: Clerks.III.2022.2160p.UHD.BluRay.x265-B0MBARDiERS\n        New Tag: PassThePopcorn\n        Tracker: http://please.passthepopcorn.me:2710/xxxx/announce\n    Share Limit: Set No Share Limit', 'torrent_name': 'Clerks.III.2022.2160p.UHD.BluRay.x265-B0MBARDiERS', 'torrent_category': 'MOVIES/RADARR', 'torrent_tag': 'PassThePopcorn', 'torrent_tracker': 'http://please.passthepopcorn.me:2710/xxxxx/announce', 'notifiarr_indexer': None, 'torrent_max_ratio': -1, 'torrent_max_seeding_time': -1, 'torrent_limit_upload_speed': 0} |
| Webhook: None                                                                                      |
| tracker url: http://p4p.arenabg.com:1337/announce                                                  |
| Uncaught Exception                                                                                 |
Traceback (most recent call last):
  File "qbit_manage.py", line 541, in <module>
    start_loop()
  File "qbit_manage.py", line 308, in start_loop
    start()
  File "qbit_manage.py", line 379, in start
    num_tagged = cfg.qbt.tags()
  File "D:\Software\qbit_manage-develop\modules\qbittorrent.py", line 287, in tags
    tracker = self.config.get_tags(torrent.trackers)
  File "D:\Software\qbit_manage-develop\modules\config.py", line 612, in get_tags
    default_tag = tracker["url"].split(os.sep)[2].split(":")[0]
IndexError: list index out of range

D:\Software\qbit_manage-develop>
```

**Comment by pax0707** [comment]
TBH I can't say what did it in the end, messed around till it managed to run without errors.
Debug was mostly useless but trace helped a lot with figuring out what went wrong.
