### ISSUE TITLE
KeyError: 'url' when tagging torrents with no hardlinks

### ISSUE THREAD

**Issue by mousecloak** [StuffAnThings/qbit_manage#63]
I'm seeing this in the logs:

```
|====================================================================================================|
|                           _     _ _                                                                |
|                          | |   (_) |                                                               |
|                      __ _| |__  _| |_   _ __ ___   __ _ _ __   __ _  __ _  ___                     |
|                     / _` | '_ \| | __| | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \                    |
|                    | (_| | |_) | | |_  | | | | | | (_| | | | | (_| | (_| |  __/                    |
|                     \__, |_.__/|_|\__| |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|                    |
|                        | |         ______                            __/ |                         |
|                        |_|        |______|                          |___/                          |
|     Version: 3.1.1                                                                                 |
|====================================================================================================|
|     --run (QBT_RUN): False                                                                         |
|     --schedule (QBT_SCHEDULE): 30                                                                  |
|     --config-file (QBT_CONFIG): config.yml                                                         |
|     --log-file (QBT_LOGFILE): activity.log                                                         |
|     --cross-seed (QBT_CROSS_SEED): False                                                           |
|     --recheck (QBT_RECHECK): False                                                                 |
|     --cat-update (QBT_CAT_UPDATE): False                                                           |
|     --tag-update (QBT_TAG_UPDATE): True                                                            |
|     --rem-unregistered (QBT_REM_UNREGISTERED): False                                               |
|     --rem-orphaned (QBT_REM_ORPHANED): True                                                        |
|     --tag-nohardlinks (QBT_TAG_NOHARDLINKS): True                                                  |
|     --skip-recycle (QBT_SKIP_RECYCLE): True                                                        |
|     --dry-run (QBT_DRY_RUN): False                                                                 |
|     --log-level (QBT_LOG_LEVEL): DEBUG                                                             |
|     --divider (QBT_DIVIDER): =                                                                     |
|     --width (QBT_WIDTH): 100                                                                       |
|     --debug (QBT_DEBUG): False                                                                     |
|     --trace (QBT_TRACE): False                                                                     |
|                                                                                                    |
|     Scheduled Mode: Running every 30 minutes.                                                      |
|====================================================================================================|
|                                            Starting Run                                            |
|====================================================================================================|
| Locating config...                                                                                 |
| Using /config/config.yml as config                                                                 |
| Config Warning: apprise attribute not found                                                        |
| Config Warning: notifiarr attribute not found                                                      |
| Connecting to Qbittorrent...                                                                       |
| Host: qbittorrent:5555, Username: admin, Password: [REDACTED]                                      |
| Qbt Connection Successful                                                                          |
|======================================= Getting Torrent List =======================================|
|========================================== Updating Tags ===========================================|
| No new torrents to tag.                                                                            |
|================================ Tagging Torrents with No Hardlinks ================================|
|    Torrent Name: a torrent                                                                         |
|       Added Tag: noHL                                                                              |
| Traceback (most recent call last):                                                                 |
|                                                                                                    |
|   File "/app/qbit_manage.py", line 283, in <module>                                                |
|     start()                                                                                        |
|                                                                                                    |
|   File "/app/qbit_manage.py", line 201, in start                                                   |
|     num_tagged,num_untagged,num_deleted,num_deleted_contents = cfg.qbt.tag_nohardlinks()           |
|                                                                                                    |
|   File "/app/modules/qbittorrent.py", line 242, in tag_nohardlinks                                 |
|     body += print_line(util.insert_space(f'Tracker: {tags["url"]}',8),loglevel)                    |
|                                                                                                    |
| KeyError: 'url'                                                                                    |
|                                                                                                    |
```

This occurs when running the latest docker `develop` tag.

Please let me know if you need a copy of my config or any other data.

**Comment by bobokun** [comment]
Update your develop branch again, it should be fixed now.

**Comment by mousecloak** [comment]
Success. Thank you for fixing this in less time it took me to write up the issue!
